# Common settings across multiple charts. These settings will be used
# by more than one chart and they ideally need to match during the
# installation of the charts consuming this values.
global:
  cattle:
    systemDefaultRegistry: ghcr.io
  skipNamespaces:
    - calico-system
    - cattle-alerting
    - cattle-ui-plugin-system
    - cattle-fleet-clusters-system
    - cattle-provisioning-capi-system
    - cattle-fleet-local-system
    - cattle-fleet-system
    - cattle-global-data
    - cattle-global-nt
    - cattle-impersonation-system
    - cattle-istio
    - cattle-logging
    - cattle-monitoring-system
    - cattle-neuvector-system
    - cattle-pipeline
    - cattle-prometheus
    - cattle-system
    - cert-manager
    - fleet-default
    - fleet-local
    - ingress-nginx
    - kube-node-lease
    - kube-public
    - kube-system
    - longhorn-system
    - rancher-operator-system
    - security-scan
    - tigera-operator
  policyServer:
    default:
      name: default
      enabled: true
