apiVersion: v2
name: kubewarden-controller
description: A Helm chart for deploying the Kubewarden stack
icon: https://www.kubewarden.io/images/icon-kubewarden.svg
type: application
kubeVersion: ">= 1.19.0"
keywords:
  - Security
  - Infrastructure
  - Monitoring
home: https://www.kubewarden.io/
maintainers:
- name: Flavio Castelli
  email: fcastelli@suse.com
- name: Rafael Fernández López
  email: rfernandezlopez@suse.com

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.2.2

annotations:
  # required ones:
  catalog.cattle.io/certified: rancher # Any application we are adding as a helm chart
  catalog.cattle.io/experimental: false # Any application that is experimental
  catalog.cattle.io/namespace: cattle-kubewarden-system # Must prefix with cattle- and suffix with -system
  catalog.cattle.io/release-name: rancher-kubewarden-controller # If this is an upstream app, prefixing with rancher is the preferred naming choice.
  catalog.cattle.io/ui-component: kubewarden # This is added for custom UI deployment of a chart
  catalog.cattle.io/display-name: Kubewarden-controller # Only for Charts with custom UI
  catalog.cattle.io/os: linux   # this means linux only, other choice here is "windows". For charts that support both, don't add this annotation

  # optional ones:
  catalog.cattle.io/requires-gvr: policyservers.policies.kubewarden.io/v1 # This type MUST be visible to the user before they can install this chart.
  catalog.cattle.io/auto-install: kubewarden-crds=match # Similar to requires but auto-installed, not manually installed. See explanation below.
  catalog.cattle.io/scope: management # Chart is only applicable to the management/local cluster and will be only shown as an option for the local cluster

  # The following two will create a UI warning if the request is not available in cluster
  # Assume the most standard setup for your chart. These can be strings with amounts, ie 64Mi or 2Gi are both valid.
  catalog.cattle.io/requests-cpu: "250m"
  catalog.cattle.io/requests-memory: "64Mi"

  catalog.cattle.io/rancher-version: ">= 2.6.0-0 <= 2.6.99-0" # Chart will only be available for users in the specified Rancher version(s), here its 2.5.0-2.5.99. This _must_ use build metadata or it won't work correctly for future RC's.
  catalog.cattle.io/kube-version: "> 18.0.0" # A SemVer range of compatible Kubernetes versions, just like Helm's kubeVersion. The difference is that ours will only hide the chart in the dashboard UI, and still allow users to edit (helm upgrade) the chart; the helm's kubeVersion disables edit in installed charts.
  catalog.cattle.io/upstream-version: "1.1.0"  # The version of the upstream chart or app. It prevents the unexpected "downgrade" when upgrading an installed chart that uses our 100.x.x+upVersion version schema.

  # Valid values for the following annotation include: `cluster-tool`, `app` or `cluster-template`
  # See the Cluster Tools section to learn more about when to set this value to `cluster-tool`.
  catalog.cattle.io/type: cluster-tool
