apiVersion: v2
name: kubewarden-controller
description: A Helm chart for deploying the Kubewarden stack
icon: https://www.kubewarden.io/images/icon-kubewarden.svg
type: application
kubeVersion: ">= 1.19.0"
keywords:
  - Security
  - Infrastructure
  - Monitoring
home: https://www.kubewarden.io/
maintainers:
- name: Flavio Castelli
  email: fcastelli@suse.com
- name: Rafael Fernández López
  email: rfernandezlopez@suse.com

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.1.0

annotations:
  # required ones:
  catalog.cattle.io/certified: rancher # Any application we are adding as a helm chart
  catalog.cattle.io/experimental: true # Any application that is experimental
  catalog.cattle.io/namespace: cattle-kubewarden-system # Must prefix with cattle- and suffix with -system
  catalog.cattle.io/release-name: rancher-kubewarden # If this is an upstream app, prefixing with rancher is the preferred naming choice.
  catalog.cattle.io/ui-component: kubewarden # This is added for custom UI deployment of a chart
  catalog.cattle.io/display-name: Kubewarden # Only for Charts with custom UI
  catalog.cattle.io/os: linux   # this means linux only, other choice here is "windows". For charts that support both, don't add this annotation

  # optional ones:
  catalog.cattle.io/requires-gvr: policyservers.policies.kubewarden.io/v1 # This type MUST be visible to the user before they can install this chart.
  catalog.cattle.io/auto-install: kubewarden-crds=match # Similar to requires but auto-installed, not manually installed. See explanation below.
